version: "3.8"
services:
        nginx:
                image: robbiefletcher2000/nginx:latest
                ports:
                        - target: 80
                          published: 80
                          protocol: tcp

                volumes:
                        - type: bind
                          source: ./nginx/nginx.conf
                          target: /etc/nginx/nginx.conf

        flask-app:
                image: robbiefletcher2000/flask-image:latest
                build: ./frontend
                ports:
                        - target: 5000
                          published: 5000
                          protocol: tcp

        backend:
                image: robbiefletcher2000/flaskback-image:latest
                build: ./backend
                ports:
                        - target: 5001
                          published: 5001
                          protocol: tcp

                environment:
                          DATABASE_URI: ${DB_URI}
                          SECRET_KEY: ${S_KEY}
